
title: surume info
author:
  name: surume
  email: sururne@gmail.com
minima:
  social_links:
    twitter_username: __surume__
    github_username:  surume
    facebook: sururne
    instagram: _surume_
    linkedin: shota-miyamoto-51872766 
theme: minima
